app/src/Entity/PrintScreen.php
<?php

namespace App\Entity;

use App\Repository\PrintScreenRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PrintScreenRepository::class)
 */
class PrintScreen
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $file_type;

    /**
     * @ORM\Column(type="boolean")
     */
    private $fail_on_error;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $scroll_to_element;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $selector;

    /**
     * @ORM\Column(type="boolean")
     */
    private $full_page;

    /**
     * @ORM\Column(type="boolean")
     */
    private $lazy_load;

    /**
     * @ORM\Column(type="integer")
     */
    private $width;

    /**
     * @ORM\Column(type="integer")
     */
    private $height;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url_image;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreateDate;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getFileType(): ?string
    {
        return $this->file_type;
    }

    public function setFileType(?string $file_type): self
    {
        $this->file_type = $file_type;

        return $this;
    }

    public function getFailOnError(): ?bool
    {
        return $this->fail_on_error;
    }

    public function setFailOnError(bool $fail_on_error): self
    {
        $this->fail_on_error = $fail_on_error;

        return $this;
    }

    public function getScrollToElement(): ?string
    {
        return $this->scroll_to_element;
    }

    public function setScrollToElement(?string $scroll_to_element): self
    {
        $this->scroll_to_element = $scroll_to_element;

        return $this;
    }

    public function getSelector(): ?string
    {
        return $this->selector;
    }

    public function setSelector(?string $selector): self
    {
        $this->selector = $selector;

        return $this;
    }

    public function getFullPage(): ?bool
    {
        return $this->full_page;
    }

    public function setFullPage(bool $full_page): self
    {
        $this->full_page = $full_page;

        return $this;
    }

    public function getLazyLoad(): ?bool
    {
        return $this->lazy_load;
    }

    public function setLazyLoad(bool $lazy_load): self
    {
        $this->lazy_load = $lazy_load;

        return $this;
    }

    public function getWidth(): ?int
    {
        return $this->width;
    }

    public function setWidth(int $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getUrl_Image(): ?string
    {
        return $this->url_image;
    }

    public function setUrlImage(?string $url_image): self
    {
        $this->url_image = $url_image;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->CreateDate;
    }

    public function setCreateDate(\DateTimeInterface $CreateDate): self
    {
        $this->CreateDate = $CreateDate;

        return $this;
    }
}

app/src/Controller/PrintScreenController.php
<?php

namespace App\Controller;

use App\Entity\PrintScreen;
use App\Form\PrintScreenType;
use App\Repository\PrintScreenRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class PrintScreenController extends AbstractController
{
    /**
     * @Route("/", name="print_screen_index", methods={"GET"})
     */
    public function index(PrintScreenRepository $printScreenRepository): Response
    {
        return $this->render('print_screen/index.html.twig', [
            'print_screens' => $printScreenRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="print_screen_show", methods={"GET"})
     */
    public function show(PrintScreen $printScreen): Response
    {
        return $this->render('print_screen/show.html.twig', [
            'print_screen' => $printScreen,
        ]);
    }

}

app/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

app/templates/print_screen/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PrintScreen index{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <h1>PrintScreen</h1>

            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Url</th>
                        <th>Image</th>
                        <th>Status</th>
                        <th>CreateDate</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for print_screen in print_screens %}
                    <tr>
                        <td>{{ print_screen.id }}</td>
                        {% if print_screen.url_image %}
                            <td><img src="{{ print_screen.url_image }}" width="50" height="50" class="img-fluid"/></td>
                        {% else %}
                            <td></td>
                        {% endif %}
                        <td>{{ print_screen.url }}</td>
                        <td>{{ print_screen.status ? 'Yes' : 'No' }}</td>
                        <td>{{ print_screen.CreateDate ? print_screen.CreateDate|date('Y-m-d H:i:s') : '' }}</td>
                        <td>
                            <a href="{{ path('print_screen_show', {'id': print_screen.id}) }}">show</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="13">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

app/templates/print_screen/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}PrintScreen{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <h1>PrintScreen</h1>
                <a href="{{ path('print_screen_index') }}">back to list</a>
                <hr />
            </div>

            <div class="col-md-4">
                <img src="{{ print_screen.url_image }}" class="img-fluid"/>
            </div>
                
            <div class="col-md-8">
            
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <td>{{ print_screen.id }}</td>
                        </tr>
                        <tr>
                            <th>Url</th>
                            <td>{{ print_screen.url }}</td>
                        </tr>
                        <tr>
                            <th>File_type</th>
                            <td>{{ print_screen.fileType }}</td>
                        </tr>
                        <tr>
                            <th>Fail_on_error</th>
                            <td>{{ print_screen.failOnError ? 'Yes' : 'No' }}</td>
                        </tr>
                        <tr>
                            <th>Scroll_to_element</th>
                            <td>{{ print_screen.scrollToElement }}</td>
                        </tr>
                        <tr>
                            <th>Selector</th>
                            <td>{{ print_screen.selector }}</td>
                        </tr>
                        <tr>
                            <th>Full_page</th>
                            <td>{{ print_screen.fullPage ? 'Yes' : 'No' }}</td>
                        </tr>
                        <tr>
                            <th>Lazy_load</th>
                            <td>{{ print_screen.lazyLoad ? 'Yes' : 'No' }}</td>
                        </tr>
                        <tr>
                            <th>Width</th>
                            <td>{{ print_screen.width }}</td>
                        </tr>
                        <tr>
                            <th>Height</th>
                            <td>{{ print_screen.height }}</td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td>{{ print_screen.status ? 'Yes' : 'No' }}</td>
                        </tr>
                        <tr>
                            <th>CreateDate</th>
                            <td>{{ print_screen.CreateDate ? print_screen.CreateDate|date('Y-m-d H:i:s') : '' }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}